INSERT IGNORE INTO stores (name) VALUES ('Mercadona');
INSERT IGNORE INTO stores (name) VALUES ('Consum');
INSERT IGNORE INTO stores (name) VALUES ('Eroski');
INSERT IGNORE INTO stores (name) VALUES ('Dia');
INSERT IGNORE INTO stores (name) VALUES ('Carrefour');
INSERT IGNORE INTO stores (name) VALUES ('Alcampo');
INSERT IGNORE INTO stores (name) VALUES ('Family Cash');
INSERT IGNORE INTO categories (name) VALUES ('Despensa');
INSERT IGNORE INTO categories (name) VALUES ('Panadería');
INSERT IGNORE INTO categories (name) VALUES ('Carne y embutidos');
INSERT IGNORE INTO categories (name) VALUES ('Pescado');
INSERT IGNORE INTO categories (name) VALUES ('Lácteos y huevos');
INSERT IGNORE INTO categories (name) VALUES ('Frutas y verduras');
INSERT IGNORE INTO categories (name) VALUES ('Platos preparados');
INSERT IGNORE INTO categories (name) VALUES ('Bebidas');
INSERT IGNORE INTO categories (name) VALUES ('Snacks y dulces');
INSERT IGNORE INTO categories (name) VALUES ('Mascotas');
INSERT IGNORE INTO categories (name) VALUES ('Herramientas');
INSERT IGNORE INTO categories (name) VALUES ('Hogar y limpieza');
INSERT IGNORE INTO categories (name) VALUES ('Cuidado personal');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Azúcar', 'Despensa', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Cacao instantáneo', 'Despensa', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Infusión', 'Despensa', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Macarrones', 'Despensa', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Espirales vegetales', 'Despensa', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Fideuá', 'Despensa', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Sal', 'Despensa', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Tomate frito', 'Despensa', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Tomate triturado', 'Despensa', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Arroz redondo', 'Despensa', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Arroz basmati', 'Despensa', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Base de pizza', 'Despensa', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Café molido mezcla', 'Despensa', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Café cappuccino', 'Despensa', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Ñoquis', 'Despensa', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Noodles', 'Despensa', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Hélices de vegetales', 'Despensa', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Guisantes', 'Despensa', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Miel', 'Despensa', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Garbanzos cocidos', 'Despensa', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Macarrones integral', 'Despensa', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Mayonesa', 'Despensa', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Salsa de quesos', 'Despensa', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Salsa de trufa', 'Despensa', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Aceitunas rellenas', 'Despensa', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Pan de aceite', 'Panadería', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Pan cristal', 'Panadería', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Pan integral', 'Panadería', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Bacon', 'Carne y embutidos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Hamburguesa', 'Carne y embutidos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Carrillada de vacuno', 'Carne y embutidos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Costilla de cerdo', 'Carne y embutidos', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Carne picada de cerdo', 'Carne y embutidos', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Carne picada de vacuno', 'Carne y embutidos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Panceta', 'Carne y embutidos', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Fuet Espetec', 'Carne y embutidos', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Mortadela con aceitunas', 'Carne y embutidos', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Chistorra', 'Carne y embutidos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Chorizo', 'Carne y embutidos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Chorizo picante', 'Carne y embutidos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Espinazo de cerdo', 'Carne y embutidos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Guanciale', 'Carne y embutidos', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Hueso de vacuno', 'Carne y embutidos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Jamón cocido', 'Carne y embutidos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Pechuga de pollo', 'Carne y embutidos', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Jamoncitos de pollo', 'Carne y embutidos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Pechuga de pavo', 'Carne y embutidos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Osobuco', 'Carne y embutidos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Atún en lata', 'Pescado', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Melva', 'Pescado', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Salmón', 'Pescado', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Calamar troceado', 'Pescado', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Bebida de almendras', 'Lácteos y huevos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Batido de vainilla', 'Lácteos y huevos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Huevos', 'Lácteos y huevos', 'Eroski');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Queso brie', 'Lácteos y huevos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Queso en dados', 'Lácteos y huevos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Queso rallado', 'Lácteos y huevos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Queso semicurado', 'Lácteos y huevos', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Queso para untar finas hierbas', 'Lácteos y huevos', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Queso Grana Padano', 'Lácteos y huevos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Queso bola', 'Lácteos y huevos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Leche entera', 'Lácteos y huevos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Leche desnatada', 'Lácteos y huevos', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Mantequilla', 'Lácteos y huevos', '');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Nata para cocinar', 'Lácteos y huevos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Yogur natural azúcar de caña', 'Lácteos y huevos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Kéfir', 'Lácteos y huevos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Queso fresco batido', 'Lácteos y huevos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Plátano', 'Frutas y verduras', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Champiñones', 'Frutas y verduras', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Espinacas', 'Frutas y verduras', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Patatas', 'Frutas y verduras', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Pera', 'Frutas y verduras', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Calabaza', 'Frutas y verduras', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Zanahoria', 'Frutas y verduras', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Ensalada', 'Frutas y verduras', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Melón Sapo', 'Frutas y verduras', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Espagueti carbonara', 'Platos preparados', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Pizza atún bacon', 'Platos preparados', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Pizza frankfurt', 'Platos preparados', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Pizza jamón serrano', 'Platos preparados', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Pizza pepperoni', 'Platos preparados', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Cocido', 'Platos preparados', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Pelota de cocido', 'Platos preparados', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Lasaña de pavo', 'Platos preparados', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Crema de verduras', 'Platos preparados', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Ensaladilla rusa', 'Platos preparados', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Empanadillas', 'Platos preparados', 'Consum');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Pasta pollo pesto', 'Platos preparados', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Caldo casero', 'Platos preparados', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Zumo con leche', 'Bebidas', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Agua', 'Bebidas', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Nestea maracuya', 'Bebidas', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Refresco de piña', 'Bebidas', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Bebida isotónica', 'Bebidas', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Monster', 'Bebidas', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Bombón almendrado', 'Snacks y dulces', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Tarrina de leche merengada', 'Snacks y dulces', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('SuperSándwich nata', 'Snacks y dulces', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Dochi tarta de la abuela', 'Snacks y dulces', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Palomitas', 'Snacks y dulces', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Patatas fritas', 'Snacks y dulces', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Snacks', 'Snacks y dulces', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Pipas', 'Snacks y dulces', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Galletas', 'Snacks y dulces', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Mousse de chocolate', 'Snacks y dulces', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Natillas con galleta', 'Snacks y dulces', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Arena para gatos', 'Mascotas', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Sopa gatos Felix', 'Mascotas', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Húmedo gatos Felix', 'Mascotas', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Pienso gatos Catisfacti', 'Mascotas', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Guantes', 'Herramientas', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Detergente lavadora', 'Hogar y limpieza', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Papel de cocina', 'Hogar y limpieza', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Papel higiénico', 'Hogar y limpieza', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Bolsas de congelación zip', 'Hogar y limpieza', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Suavizante ropa', 'Hogar y limpieza', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Lavavajillas', 'Hogar y limpieza', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Limpiacristales', 'Hogar y limpieza', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Fregona microfibra', 'Hogar y limpieza', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Fregasuelos', 'Hogar y limpieza', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Limpiador WC', 'Hogar y limpieza', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Torcamans', 'Hogar y limpieza', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Jabón de manos', 'Hogar y limpieza', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Detergente lavadora', 'Hogar y limpieza', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Vela vaso aromática', 'Hogar y limpieza', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Mascarilla capilar', 'Cuidado personal', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Desodorante roll-on', 'Cuidado personal', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Pimiento congelado variado', 'Platos preparados', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Mini empanadillas de queso', 'Snacks y dulces', 'Consum');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Jamón serrano', 'Carne y embutidos', 'Mercadona');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Toallitas de baño', 'Cuidado personal', 'Family Cash');
INSERT IGNORE INTO products (name, category_name, preferred_store) VALUES ('Queso en lonchas', 'Lácteos y huevos', 'Mercadona');
